spring:
  cloud:
    stream:
      bindings:
        BYTE_STREAM_OUT_PUT:
          destination: BYTE-STREAM-2
          contentType: application/octet-stream
        BYTE_STREAM_IN_PUT:
          destination: BYTE-STREAM-2
          contentType: application/octet-stream
        JSON_STREAM_OUT_PUT:
          destination: JSON-STREAM #通道地址,默认contentType是json
        JSON_STREAM_IN_PUT:
          destination: JSON-STREAM
        TEXT_STREAM_OUT_PUT:
          destination: TEXT-STREAM
          contentType: text/plain
        TEXT_STREAM_IN_PUT:
          destination: TEXT-STREAM
          contentType: text/plain
        SOURCE_MESSAGE_IN_PUT:
          destination: SOURCE-STREAM
          contentType: text/plain
        SOURCE_MESSAGE_OUT_PUT:
          destination: SOURCE-STREAM
          contentType: text/plain
          group: source
        POLLABLE_CHANNEL_OUT_PUT:
          destination: SOURCE-STREAM
          contentType: text/plain
        POLLABLE_CHANNEL_IN_PUT:
          destination: SOURCE-STREAM
          contentType: text/plain
          group: poll
      redis:
        binder:
          redisson-config-yaml-file: redisson.yml
          #redisson-config-yaml-file: classpath:redisson.yml
          #redisson-config-yaml-file: file:C:\Users\lhstack\Desktop\spring-cloud-stream-redis\spring-cloud-stream-redis2-tests\src\main\resources\redisson.yml
server:
  port: 8080